dist: trusty
language: c

cache:
  directories:
  - $HOME/.opam

env:
  global:
  - OPAMJOBS="2"
  - OPAMYES="true"
  - OPAMVERBOSE="true"
  matrix:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.0
  - OCAML_VERSION=4.07.1

before_install:
  # Obtain and install opam locally.
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  # Initialize the switch.
  - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
  - opam update
  - opam switch "$OCAML_VERSION"
  - eval $(opam env)
  - opam install ocamlbuild ocamlfind bindlib.5.0.1 earley.2.0.0

script:
  - make
  - make install
  - make tests

script:
  - make $TEST_TARGETS

notifications:
  email:
    - christophe@raffalli.eu
    - rodolphe.lepigre@inria.fr
